version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5000"
  backend:
    build: ./backend
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - frontend
